# config/__init__.py
"""配置模块"""

from .settings import (
    DEFAULT_CONFIG,
    SUPPORTED_OUTPUT_FORMATS,
    SEARCH_ENGINE_CONFIGS,
    URL_RESOLVER_CONFIGS,
    DEFAULT_HEADERS,
    HTML_REPORT_TEMPLATE
)

__all__ = [
    "DEFAULT_CONFIG",
    "SUPPORTED_OUTPUT_FORMATS", 
    "SEARCH_ENGINE_CONFIGS",
    "URL_RESOLVER_CONFIGS",
    "DEFAULT_HEADERS",
    "HTML_REPORT_TEMPLATE"
]
